---
- name: Sample Ansible Playbook
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Install apache httpd (state=present is optional)
      ansible.builtin.apt:
        name: apache2
